### PR TITLE
Add Chinese Docs

### PR DESCRIPTION
**Pull request by Mister-Hope**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Hi bro, i helped you create the CHinese docs. 👍

**Comment by Mister-Hope** [comment]
Hey bro @ulivz , busy with something? ::smile: Could you spend some time to have a look at this PR?

**Comment by newsbielt703** [comment]
👍  

 I'll review it these days.

**Comment by newsbielt703** [comment]
@Mister-Hope Thank you for your contribution and sorry for late reply. We decide to add translations after the documentation is  complete or stable enough to prevent it causing extra efforts in the future.

**Comment by Mister-Hope** [comment]
Hey, is the plugin stable enough now?

**Comment by newsbielt703** [comment]
Yes, it is. Welcome!

**Pull request closed without merging**
